# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            shaobo
tagline:          'start a new life'
url:              http://shaobo.github.io/blogs/

author:
  name:           'shaobo'
  url:            http://shaobo.github.io/blogs/

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/shaobo/blogs

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
